import type { Championship, StandingRow, EnrolledTeam, Player, Invite, Match, ChampionStat } from "@/types"

// ─── Championships ────────────────────────────────────────────
export const mockChampionships: Championship[] = [
  {
    id: 1,
    name: "ArenaBR Season 1",
    description: "O primeiro campeonato oficial da ArenaBR. Formato eliminação dupla, 8 times.",
    status: "ongoing",
    prize_pool: 500,
    entry_fee: 100,
    max_teams: 8,
    enrolled_teams: 6,
    start_date: "2026-04-01",
    end_date: "2026-05-01",
    format: "Eliminação Dupla",
    banner_url: null,
  },
  {
    id: 2,
    name: "ArenaBR Cup — Invitational",
    description: "Campeonato por convite para os melhores times da Season 1.",
    status: "open",
    prize_pool: 1000,
    entry_fee: 100,
    max_teams: 4,
    enrolled_teams: 1,
    start_date: "2026-05-10",
    end_date: "2026-05-25",
    format: "Round Robin + Final",
    banner_url: null,
  },
]

// ─── Standings ────────────────────────────────────────────────
export const mockStandings: StandingRow[] = [
  { position: 1, team_id: 1, team_name: "Wolves BR",       team_logo: null, wins: 4, losses: 0, match_diff: 8  },
  { position: 2, team_id: 2, team_name: "Dark Knights",    team_logo: null, wins: 3, losses: 1, match_diff: 4  },
  { position: 3, team_id: 3, team_name: "Phantom Esports", team_logo: null, wins: 2, losses: 2, match_diff: 0  },
  { position: 4, team_id: 4, team_name: "Red Storm",       team_logo: null, wins: 2, losses: 2, match_diff: -1 },
  { position: 5, team_id: 5, team_name: "Zero Hour",       team_logo: null, wins: 1, losses: 3, match_diff: -4 },
  { position: 6, team_id: 6, team_name: "Neon Renegades",  team_logo: null, wins: 0, losses: 4, match_diff: -7 },
]

// ─── Enrolled Teams ───────────────────────────────────────────
export const mockEnrolledTeams: EnrolledTeam[] = [
  {
    id: 1,
    org_name: "Wolves BR",
    org_logo: null,
    org_region: "BR",
    wins: 4,
    losses: 0,
    match_diff: 8,
    payment_status: "confirmed",
    enrolled_at: "2026-03-28",
    players: [
      { id: 1, summoner_name: "WolfAlpha#BR1",  role: "top",     current_rank: "Diamond IV (45 LP)",  avatar_url: null, is_captain: true  },
      { id: 2, summoner_name: "Fangs#0001",     role: "jungle",  current_rank: "Platinum II (78 LP)", avatar_url: null, is_captain: false },
      { id: 3, summoner_name: "Howler#BR2",     role: "mid",     current_rank: "Platinum I (12 LP)",  avatar_url: null, is_captain: false },
      { id: 4, summoner_name: "WolfBot#0007",   role: "adc",     current_rank: "Gold I (55 LP)",      avatar_url: null, is_captain: false },
      { id: 5, summoner_name: "Moonhowl#BR1",   role: "support", current_rank: "Platinum III (30 LP)",avatar_url: null, is_captain: false },
    ],
  },
  {
    id: 2,
    org_name: "Dark Knights",
    org_logo: null,
    org_region: "BR",
    wins: 3,
    losses: 1,
    match_diff: 4,
    payment_status: "confirmed",
    enrolled_at: "2026-03-29",
    players: [
      { id: 6,  summoner_name: "DKnight#BR1",  role: "top",     current_rank: "Platinum IV (60 LP)", avatar_url: null, is_captain: true  },
      { id: 7,  summoner_name: "ShadowJG#001", role: "jungle",  current_rank: "Gold I (80 LP)",      avatar_url: null, is_captain: false },
      { id: 8,  summoner_name: "DarkMage#BR1", role: "mid",     current_rank: "Gold II (45 LP)",     avatar_url: null, is_captain: false },
      { id: 9,  summoner_name: "NightShot#0",  role: "adc",     current_rank: "Gold I (20 LP)",      avatar_url: null, is_captain: false },
      { id: 10, summoner_name: "VoidHeal#BR1", role: "support", current_rank: "Platinum IV (10 LP)", avatar_url: null, is_captain: false },
    ],
  },
  {
    id: 3,
    org_name: "Phantom Esports",
    org_logo: null,
    org_region: "BR",
    wins: 2,
    losses: 2,
    match_diff: 0,
    payment_status: "confirmed",
    enrolled_at: "2026-03-30",
    players: [
      { id: 11, summoner_name: "PhantomT#BR1", role: "top",     current_rank: "Gold I (70 LP)",     avatar_url: null, is_captain: true  },
      { id: 12, summoner_name: "GhostJG#001",  role: "jungle",  current_rank: "Gold III (25 LP)",   avatar_url: null, is_captain: false },
      { id: 13, summoner_name: "SpectreM#BR1", role: "mid",     current_rank: "Gold II (55 LP)",    avatar_url: null, is_captain: false },
      { id: 14, summoner_name: "WraithAD#0",   role: "adc",     current_rank: "Silver I (90 LP)",   avatar_url: null, is_captain: false },
      { id: 15, summoner_name: "MistSup#BR1",  role: "support", current_rank: "Gold II (40 LP)",    avatar_url: null, is_captain: false },
    ],
  },
  {
    id: 4,
    org_name: "Red Storm",
    org_logo: null,
    org_region: "BR",
    wins: 2,
    losses: 2,
    match_diff: -1,
    payment_status: "confirmed",
    enrolled_at: "2026-03-30",
    players: [
      { id: 16, summoner_name: "StormTop#BR1",  role: "top",     current_rank: "Silver I (50 LP)",  avatar_url: null, is_captain: true  },
      { id: 17, summoner_name: "ThunderJG#01",  role: "jungle",  current_rank: "Gold IV (75 LP)",   avatar_url: null, is_captain: false },
      { id: 18, summoner_name: "LightningM#1",  role: "mid",     current_rank: "Silver I (30 LP)",  avatar_url: null, is_captain: false },
      { id: 19, summoner_name: "BoltADC#BR1",   role: "adc",     current_rank: "Silver II (60 LP)", avatar_url: null, is_captain: false },
      { id: 20, summoner_name: "RainSup#001",   role: "support", current_rank: "Silver III (20 LP)",avatar_url: null, is_captain: false },
    ],
  },
]

// ─── Players (espelha PlayerSerializer do prostaff-api) ────────
// Fallback quando /api/players não retorna dados
export const mockPlayers: Player[] = [
  {
    id: 1,
    summoner_name: "WolfAlpha#BR1",
    professional_name: "Wolf",
    real_name: null,
    role: "top",
    status: "active",
    riot_puuid: "abc1",
    solo_queue_tier: "DIAMOND",
    solo_queue_rank: "IV",
    solo_queue_lp: 45,
    solo_queue_wins: 120,
    solo_queue_losses: 95,
    current_rank: "Diamond IV (45 LP)",
    win_rate: 56,
    profile_icon_id: 4357,
    avatar_url: null,
    discord_user_id: "WolfAlpha#1234",
    jersey_number: 1,
    contract_status: "active",
    last_sync_at: "2026-04-09T10:00:00Z",
    sync_status: "synced",
  },
  {
    id: 2,
    summoner_name: "Fangs#0001",
    professional_name: "Fangs",
    real_name: null,
    role: "jungle",
    status: "active",
    riot_puuid: "abc2",
    solo_queue_tier: "PLATINUM",
    solo_queue_rank: "II",
    solo_queue_lp: 78,
    solo_queue_wins: 200,
    solo_queue_losses: 180,
    current_rank: "Platinum II (78 LP)",
    win_rate: 53,
    profile_icon_id: 4001,
    avatar_url: null,
    discord_user_id: "Fangs#5678",
    jersey_number: 2,
    contract_status: "active",
    last_sync_at: "2026-04-09T10:00:00Z",
    sync_status: "synced",
  },
  {
    id: 3,
    summoner_name: "Howler#BR2",
    professional_name: null,
    real_name: null,
    role: "mid",
    status: "active",
    riot_puuid: "abc3",
    solo_queue_tier: "PLATINUM",
    solo_queue_rank: "I",
    solo_queue_lp: 12,
    solo_queue_wins: 150,
    solo_queue_losses: 140,
    current_rank: "Platinum I (12 LP)",
    win_rate: 52,
    profile_icon_id: 3987,
    avatar_url: null,
    discord_user_id: null,
    jersey_number: 3,
    contract_status: "active",
    last_sync_at: "2026-04-09T10:00:00Z",
    sync_status: "synced",
  },
  {
    id: 4,
    summoner_name: "WolfBot#0007",
    professional_name: null,
    real_name: null,
    role: "adc",
    status: "active",
    riot_puuid: "abc4",
    solo_queue_tier: "GOLD",
    solo_queue_rank: "I",
    solo_queue_lp: 55,
    solo_queue_wins: 90,
    solo_queue_losses: 80,
    current_rank: "Gold I (55 LP)",
    win_rate: 53,
    profile_icon_id: 4100,
    avatar_url: null,
    discord_user_id: "WolfBot#9999",
    jersey_number: 4,
    contract_status: "active",
    last_sync_at: "2026-04-09T10:00:00Z",
    sync_status: "synced",
  },
  {
    id: 5,
    summoner_name: "Moonhowl#BR1",
    professional_name: null,
    real_name: null,
    role: "support",
    status: "active",
    riot_puuid: "abc5",
    solo_queue_tier: "PLATINUM",
    solo_queue_rank: "III",
    solo_queue_lp: 30,
    solo_queue_wins: 110,
    solo_queue_losses: 100,
    current_rank: "Platinum III (30 LP)",
    win_rate: 52,
    profile_icon_id: 3500,
    avatar_url: null,
    discord_user_id: null,
    jersey_number: 5,
    contract_status: "active",
    last_sync_at: "2026-04-09T10:00:00Z",
    sync_status: "synced",
  },
]

// ─── Free agents (jogadores sem org inscritos no campeonato) ───
export const mockFreeAgents: Player[] = [
  {
    id: 21,
    summoner_name: "FreeWolf#BR1",
    professional_name: null,
    real_name: null,
    role: "top",
    status: "active",
    riot_puuid: "abc21",
    solo_queue_tier: "PLATINUM",
    solo_queue_rank: "III",
    solo_queue_lp: 30,
    solo_queue_wins: 80,
    solo_queue_losses: 70,
    current_rank: "Platinum III (30 LP)",
    win_rate: 53,
    profile_icon_id: 4200,
    avatar_url: null,
    discord_user_id: "FreeWolf#0001",
    jersey_number: null,
    contract_status: null,
    last_sync_at: null,
    sync_status: null,
  },
  {
    id: 22,
    summoner_name: "SoloCarry#001",
    professional_name: null,
    real_name: null,
    role: "mid",
    status: "active",
    riot_puuid: "abc22",
    solo_queue_tier: "GOLD",
    solo_queue_rank: "I",
    solo_queue_lp: 90,
    solo_queue_wins: 60,
    solo_queue_losses: 50,
    current_rank: "Gold I (90 LP)",
    win_rate: 55,
    profile_icon_id: 3800,
    avatar_url: null,
    discord_user_id: "SoloCarry#2222",
    jersey_number: null,
    contract_status: null,
    last_sync_at: null,
    sync_status: null,
  },
  {
    id: 23,
    summoner_name: "Nomad#BR1",
    professional_name: null,
    real_name: null,
    role: "jungle",
    status: "active",
    riot_puuid: "abc23",
    solo_queue_tier: "GOLD",
    solo_queue_rank: "II",
    solo_queue_lp: 55,
    solo_queue_wins: 45,
    solo_queue_losses: 42,
    current_rank: "Gold II (55 LP)",
    win_rate: 52,
    profile_icon_id: 3600,
    avatar_url: null,
    discord_user_id: null,
    jersey_number: null,
    contract_status: null,
    last_sync_at: null,
    sync_status: null,
  },
]

// ─── Invites ──────────────────────────────────────────────────
export const mockInvites: Invite[] = [
  {
    id: 1,
    team_id: 1,
    team_name: "Wolves BR",
    team_logo: null,
    captain_summoner_name: "WolfAlpha#BR1",
    championship_name: "ArenaBR Season 1",
    status: "pending",
    created_at: "2026-04-08T14:30:00Z",
  },
]

// ─── Matches ──────────────────────────────────────────────────
// Campeonato 1 — ArenaBR Season 1 (eliminação dupla, 8 times)
// Teams: 1=Wolves BR, 2=Dark Knights, 3=Phantom Esports, 4=Red Storm
//         5=Zero Hour, 6=Neon Renegades, 7=Eclipse Gaming, 8=Iron Wolves

export const mockMatches: Match[] = [
  // ── Upper Bracket Round 1 ─────────────────────────────────
  {
    id: 1,
    championship_id: 1,
    bracket_side: "upper",
    round: "UB R1",
    round_order: 1,
    match_number: 1,
    team_a_id: 1, team_a_name: "Wolves BR",       team_a_logo: null, team_a_score: 2,
    team_b_id: 8, team_b_name: "Iron Wolves",      team_b_logo: null, team_b_score: 0,
    status: "completed",
    scheduled_at: "2026-04-05T15:00:00Z",
    winner_id: 1,
    games: [
      {
        id: 1, match_id: 1, game_number: 1, duration_seconds: 1845, winner_id: 1,
        blue_team_id: 1, red_team_id: 8,
        player_stats: [
          { player_id: 1, summoner_name: "WolfAlpha#BR1", team_id: 1, team_name: "Wolves BR",  side: "blue", role: "top",     champion_name: "Garen",   kills: 5,  deaths: 1, assists: 8,  kda: 13.0, cs: 210, gold: 14200, damage_dealt: 28000, vision_score: 18 },
          { player_id: 2, summoner_name: "Fangs#0001",    team_id: 1, team_name: "Wolves BR",  side: "blue", role: "jungle",  champion_name: "Vi",      kills: 8,  deaths: 2, assists: 12, kda: 10.0, cs: 185, gold: 15800, damage_dealt: 22000, vision_score: 32 },
          { player_id: 3, summoner_name: "Howler#BR2",    team_id: 1, team_name: "Wolves BR",  side: "blue", role: "mid",     champion_name: "Syndra",  kills: 11, deaths: 1, assists: 7,  kda: 18.0, cs: 260, gold: 18500, damage_dealt: 38000, vision_score: 22 },
          { player_id: 4, summoner_name: "WolfBot#0007",  team_id: 1, team_name: "Wolves BR",  side: "blue", role: "adc",     champion_name: "Jinx",    kills: 9,  deaths: 0, assists: 10, kda: 19.0, cs: 285, gold: 19200, damage_dealt: 42000, vision_score: 15 },
          { player_id: 5, summoner_name: "Moonhowl#BR1",  team_id: 1, team_name: "Wolves BR",  side: "blue", role: "support", champion_name: "Thresh",  kills: 1,  deaths: 2, assists: 22, kda: 11.5, cs: 18,  gold: 9800,  damage_dealt: 6500,  vision_score: 55 },
          { player_id: 31, summoner_name: "IronT#BR1",   team_id: 8, team_name: "Iron Wolves", side: "red",  role: "top",     champion_name: "Darius",  kills: 1,  deaths: 6, assists: 3,  kda: 0.67, cs: 178, gold: 10200, damage_dealt: 15000, vision_score: 14 },
          { player_id: 32, summoner_name: "IronJG#001",  team_id: 8, team_name: "Iron Wolves", side: "red",  role: "jungle",  champion_name: "Jarvan",  kills: 2,  deaths: 5, assists: 4,  kda: 1.2,  cs: 145, gold: 9800,  damage_dealt: 12000, vision_score: 28 },
          { player_id: 33, summoner_name: "IronMid#BR1", team_id: 8, team_name: "Iron Wolves", side: "red",  role: "mid",     champion_name: "Zed",     kills: 4,  deaths: 6, assists: 2,  kda: 1.0,  cs: 220, gold: 12400, damage_dealt: 20000, vision_score: 18 },
          { player_id: 34, summoner_name: "IronADC#0",   team_id: 8, team_name: "Iron Wolves", side: "red",  role: "adc",     champion_name: "Caitlyn", kills: 3,  deaths: 7, assists: 3,  kda: 0.86, cs: 230, gold: 11800, damage_dealt: 18000, vision_score: 12 },
          { player_id: 35, summoner_name: "IronSup#BR1", team_id: 8, team_name: "Iron Wolves", side: "red",  role: "support", champion_name: "Lux",     kills: 0,  deaths: 5, assists: 5,  kda: 1.0,  cs: 12,  gold: 7200,  damage_dealt: 8000,  vision_score: 38 },
        ],
      },
      {
        id: 2, match_id: 1, game_number: 2, duration_seconds: 1620, winner_id: 1,
        blue_team_id: 8, red_team_id: 1,
        player_stats: [
          { player_id: 1, summoner_name: "WolfAlpha#BR1", team_id: 1, team_name: "Wolves BR",  side: "red",  role: "top",     champion_name: "Fiora",   kills: 7,  deaths: 2, assists: 5,  kda: 6.0,  cs: 225, gold: 15800, damage_dealt: 32000, vision_score: 20 },
          { player_id: 2, summoner_name: "Fangs#0001",    team_id: 1, team_name: "Wolves BR",  side: "red",  role: "jungle",  champion_name: "Hecarim", kills: 6,  deaths: 1, assists: 14, kda: 20.0, cs: 195, gold: 14900, damage_dealt: 19000, vision_score: 35 },
          { player_id: 3, summoner_name: "Howler#BR2",    team_id: 1, team_name: "Wolves BR",  side: "red",  role: "mid",     champion_name: "Azir",    kills: 9,  deaths: 2, assists: 8,  kda: 8.5,  cs: 270, gold: 17800, damage_dealt: 35000, vision_score: 25 },
          { player_id: 4, summoner_name: "WolfBot#0007",  team_id: 1, team_name: "Wolves BR",  side: "red",  role: "adc",     champion_name: "Aphelios",kills: 12, deaths: 1, assists: 7,  kda: 19.0, cs: 295, gold: 20100, damage_dealt: 45000, vision_score: 14 },
          { player_id: 5, summoner_name: "Moonhowl#BR1",  team_id: 1, team_name: "Wolves BR",  side: "red",  role: "support", champion_name: "Nautilus",kills: 0,  deaths: 1, assists: 25, kda: 25.0, cs: 14,  gold: 9200,  damage_dealt: 5800,  vision_score: 60 },
          { player_id: 31, summoner_name: "IronT#BR1",   team_id: 8, team_name: "Iron Wolves", side: "blue", role: "top",     champion_name: "Malphite",kills: 2,  deaths: 7, assists: 4,  kda: 0.86, cs: 168, gold: 9400,  damage_dealt: 13000, vision_score: 16 },
          { player_id: 32, summoner_name: "IronJG#001",  team_id: 8, team_name: "Iron Wolves", side: "blue", role: "jungle",  champion_name: "Graves",  kills: 3,  deaths: 6, assists: 5,  kda: 1.33, cs: 160, gold: 10200, damage_dealt: 14000, vision_score: 22 },
          { player_id: 33, summoner_name: "IronMid#BR1", team_id: 8, team_name: "Iron Wolves", side: "blue", role: "mid",     champion_name: "Viktor",  kills: 5,  deaths: 8, assists: 3,  kda: 1.0,  cs: 240, gold: 13200, damage_dealt: 22000, vision_score: 20 },
          { player_id: 34, summoner_name: "IronADC#0",   team_id: 8, team_name: "Iron Wolves", side: "blue", role: "adc",     champion_name: "Ezreal",  kills: 4,  deaths: 6, assists: 6,  kda: 1.67, cs: 215, gold: 11600, damage_dealt: 17000, vision_score: 10 },
          { player_id: 35, summoner_name: "IronSup#BR1", team_id: 8, team_name: "Iron Wolves", side: "blue", role: "support", champion_name: "Blitzcrank",kills:0, deaths: 7, assists: 8,  kda: 1.14, cs: 8,   gold: 6800,  damage_dealt: 5200,  vision_score: 42 },
        ],
      },
    ],
  },
  {
    id: 2,
    championship_id: 1,
    bracket_side: "upper",
    round: "UB R1",
    round_order: 1,
    match_number: 2,
    team_a_id: 2, team_a_name: "Dark Knights",    team_a_logo: null, team_a_score: 2,
    team_b_id: 7, team_b_name: "Eclipse Gaming",  team_b_logo: null, team_b_score: 1,
    status: "completed",
    scheduled_at: "2026-04-05T17:00:00Z",
    winner_id: 2,
    games: [
      {
        id: 3, match_id: 2, game_number: 1, duration_seconds: 2100, winner_id: 7,
        blue_team_id: 2, red_team_id: 7,
        player_stats: [
          { player_id: 6,  summoner_name: "DKnight#BR1",  team_id: 2, team_name: "Dark Knights",   side: "blue", role: "top",     champion_name: "Camille",  kills: 3, deaths: 5, assists: 6, kda: 1.8, cs: 195, gold: 12800, damage_dealt: 22000, vision_score: 16 },
          { player_id: 7,  summoner_name: "ShadowJG#001", team_id: 2, team_name: "Dark Knights",   side: "blue", role: "jungle",  champion_name: "Nidalee",  kills: 4, deaths: 4, assists: 8, kda: 3.0, cs: 155, gold: 12200, damage_dealt: 15000, vision_score: 30 },
          { player_id: 8,  summoner_name: "DarkMage#BR1", team_id: 2, team_name: "Dark Knights",   side: "blue", role: "mid",     champion_name: "LeBlanc",  kills: 7, deaths: 3, assists: 5, kda: 4.0, cs: 235, gold: 16200, damage_dealt: 30000, vision_score: 22 },
          { player_id: 9,  summoner_name: "NightShot#0",  team_id: 2, team_name: "Dark Knights",   side: "blue", role: "adc",     champion_name: "Jhin",     kills: 6, deaths: 3, assists: 9, kda: 5.0, cs: 255, gold: 16800, damage_dealt: 34000, vision_score: 14 },
          { player_id: 10, summoner_name: "VoidHeal#BR1", team_id: 2, team_name: "Dark Knights",   side: "blue", role: "support", champion_name: "Zyra",     kills: 2, deaths: 4, assists: 16,kda: 4.5, cs: 22,  gold: 9400,  damage_dealt: 12000, vision_score: 48 },
          { player_id: 26, summoner_name: "EclipseT#BR1", team_id: 7, team_name: "Eclipse Gaming", side: "red",  role: "top",     champion_name: "Jax",      kills: 8, deaths: 4, assists: 7, kda: 3.75,cs: 210, gold: 15400, damage_dealt: 28000, vision_score: 18 },
          { player_id: 27, summoner_name: "SolarJG#001",  team_id: 7, team_name: "Eclipse Gaming", side: "red",  role: "jungle",  champion_name: "Kha'Zix",  kills: 6, deaths: 3, assists: 10,kda: 5.33,cs: 170, gold: 14200, damage_dealt: 20000, vision_score: 28 },
          { player_id: 28, summoner_name: "LunarMid#BR1", team_id: 7, team_name: "Eclipse Gaming", side: "red",  role: "mid",     champion_name: "Orianna",  kills: 5, deaths: 2, assists: 14,kda: 9.5, cs: 245, gold: 15800, damage_dealt: 26000, vision_score: 24 },
          { player_id: 29, summoner_name: "NightADC#0",   team_id: 7, team_name: "Eclipse Gaming", side: "red",  role: "adc",     champion_name: "Tristana", kills: 10,deaths: 2, assists: 8, kda: 9.0, cs: 270, gold: 18200, damage_dealt: 38000, vision_score: 12 },
          { player_id: 30, summoner_name: "StarSup#BR1",  team_id: 7, team_name: "Eclipse Gaming", side: "red",  role: "support", champion_name: "Leona",    kills: 1, deaths: 3, assists: 20,kda: 7.0, cs: 16,  gold: 8800,  damage_dealt: 7500,  vision_score: 52 },
        ],
      },
      {
        id: 4, match_id: 2, game_number: 2, duration_seconds: 1920, winner_id: 2,
        blue_team_id: 7, red_team_id: 2,
        player_stats: [
          { player_id: 6,  summoner_name: "DKnight#BR1",  team_id: 2, team_name: "Dark Knights",   side: "red",  role: "top",     champion_name: "Renekton", kills: 9, deaths: 2, assists: 7, kda: 8.0, cs: 220, gold: 16400, damage_dealt: 32000, vision_score: 18 },
          { player_id: 7,  summoner_name: "ShadowJG#001", team_id: 2, team_name: "Dark Knights",   side: "red",  role: "jungle",  champion_name: "Lee Sin",  kills: 5, deaths: 1, assists: 14,kda: 19.0,cs: 180, gold: 14600, damage_dealt: 16000, vision_score: 34 },
          { player_id: 8,  summoner_name: "DarkMage#BR1", team_id: 2, team_name: "Dark Knights",   side: "red",  role: "mid",     champion_name: "Sylas",    kills: 8, deaths: 2, assists: 9, kda: 8.5, cs: 248, gold: 17200, damage_dealt: 36000, vision_score: 24 },
          { player_id: 9,  summoner_name: "NightShot#0",  team_id: 2, team_name: "Dark Knights",   side: "red",  role: "adc",     champion_name: "Xayah",    kills: 11,deaths: 1, assists: 8, kda: 19.0,cs: 278, gold: 19600, damage_dealt: 44000, vision_score: 15 },
          { player_id: 10, summoner_name: "VoidHeal#BR1", team_id: 2, team_name: "Dark Knights",   side: "red",  role: "support", champion_name: "Rakan",    kills: 2, deaths: 1, assists: 22,kda: 24.0,cs: 12,  gold: 10200, damage_dealt: 8000,  vision_score: 58 },
          { player_id: 26, summoner_name: "EclipseT#BR1", team_id: 7, team_name: "Eclipse Gaming", side: "blue", role: "top",     champion_name: "Aatrox",   kills: 4, deaths: 7, assists: 5, kda: 1.29,cs: 190, gold: 11800, damage_dealt: 22000, vision_score: 16 },
          { player_id: 27, summoner_name: "SolarJG#001",  team_id: 7, team_name: "Eclipse Gaming", side: "blue", role: "jungle",  champion_name: "Viego",    kills: 3, deaths: 5, assists: 8, kda: 2.2, cs: 158, gold: 11200, damage_dealt: 14000, vision_score: 26 },
          { player_id: 28, summoner_name: "LunarMid#BR1", team_id: 7, team_name: "Eclipse Gaming", side: "blue", role: "mid",     champion_name: "Irelia",   kills: 6, deaths: 6, assists: 4, kda: 1.67,cs: 228, gold: 14200, damage_dealt: 25000, vision_score: 22 },
          { player_id: 29, summoner_name: "NightADC#0",   team_id: 7, team_name: "Eclipse Gaming", side: "blue", role: "adc",     champion_name: "Draven",   kills: 5, deaths: 7, assists: 6, kda: 1.57,cs: 248, gold: 14800, damage_dealt: 28000, vision_score: 11 },
          { player_id: 30, summoner_name: "StarSup#BR1",  team_id: 7, team_name: "Eclipse Gaming", side: "blue", role: "support", champion_name: "Alistar",  kills: 1, deaths: 5, assists: 10,kda: 2.2, cs: 10,  gold: 7600,  damage_dealt: 5800,  vision_score: 44 },
        ],
      },
      {
        id: 5, match_id: 2, game_number: 3, duration_seconds: 2340, winner_id: 2,
        blue_team_id: 2, red_team_id: 7,
        player_stats: [
          { player_id: 6,  summoner_name: "DKnight#BR1",  team_id: 2, team_name: "Dark Knights",   side: "blue", role: "top",     champion_name: "Gwen",    kills: 6, deaths: 3, assists: 8, kda: 4.67,cs: 240, gold: 16800, damage_dealt: 30000, vision_score: 20 },
          { player_id: 7,  summoner_name: "ShadowJG#001", team_id: 2, team_name: "Dark Knights",   side: "blue", role: "jungle",  champion_name: "Kindred",  kills: 4, deaths: 2, assists: 15,kda: 9.5, cs: 200, gold: 15200, damage_dealt: 18000, vision_score: 36 },
          { player_id: 8,  summoner_name: "DarkMage#BR1", team_id: 2, team_name: "Dark Knights",   side: "blue", role: "mid",     champion_name: "Lissandra",kills: 7, deaths: 3, assists: 10,kda: 5.67,cs: 255, gold: 17400, damage_dealt: 33000, vision_score: 26 },
          { player_id: 9,  summoner_name: "NightShot#0",  team_id: 2, team_name: "Dark Knights",   side: "blue", role: "adc",     champion_name: "Kalista",  kills: 10,deaths: 2, assists: 9, kda: 9.5, cs: 290, gold: 20400, damage_dealt: 46000, vision_score: 16 },
          { player_id: 10, summoner_name: "VoidHeal#BR1", team_id: 2, team_name: "Dark Knights",   side: "blue", role: "support", champion_name: "Thresh",  kills: 1, deaths: 2, assists: 24,kda: 12.5,cs: 14,  gold: 9800,  damage_dealt: 7200,  vision_score: 62 },
          { player_id: 26, summoner_name: "EclipseT#BR1", team_id: 7, team_name: "Eclipse Gaming", side: "red",  role: "top",     champion_name: "Darius",  kills: 5, deaths: 8, assists: 6, kda: 1.38,cs: 200, gold: 13200, damage_dealt: 24000, vision_score: 18 },
          { player_id: 27, summoner_name: "SolarJG#001",  team_id: 7, team_name: "Eclipse Gaming", side: "red",  role: "jungle",  champion_name: "Evelynn", kills: 5, deaths: 6, assists: 8, kda: 2.17,cs: 170, gold: 12400, damage_dealt: 18000, vision_score: 28 },
          { player_id: 28, summoner_name: "LunarMid#BR1", team_id: 7, team_name: "Eclipse Gaming", side: "red",  role: "mid",     champion_name: "Katarina",kills: 8, deaths: 7, assists: 5, kda: 1.86,cs: 238, gold: 15200, damage_dealt: 28000, vision_score: 22 },
          { player_id: 29, summoner_name: "NightADC#0",   team_id: 7, team_name: "Eclipse Gaming", side: "red",  role: "adc",     champion_name: "Sivir",   kills: 4, deaths: 8, assists: 10,kda: 1.75,cs: 262, gold: 14600, damage_dealt: 26000, vision_score: 12 },
          { player_id: 30, summoner_name: "StarSup#BR1",  team_id: 7, team_name: "Eclipse Gaming", side: "red",  role: "support", champion_name: "Seraphine",kills:2, deaths: 7, assists: 12,kda: 2.0, cs: 18,  gold: 8400,  damage_dealt: 9500,  vision_score: 46 },
        ],
      },
    ],
  },
  {
    id: 3,
    championship_id: 1,
    bracket_side: "upper",
    round: "UB R1",
    round_order: 1,
    match_number: 3,
    team_a_id: 3, team_a_name: "Phantom Esports", team_a_logo: null, team_a_score: 2,
    team_b_id: 6, team_b_name: "Neon Renegades",  team_b_logo: null, team_b_score: 0,
    status: "completed",
    scheduled_at: "2026-04-06T15:00:00Z",
    winner_id: 3,
    games: [],
  },
  {
    id: 4,
    championship_id: 1,
    bracket_side: "upper",
    round: "UB R1",
    round_order: 1,
    match_number: 4,
    team_a_id: 4, team_a_name: "Red Storm",       team_a_logo: null, team_a_score: 2,
    team_b_id: 5, team_b_name: "Zero Hour",       team_b_logo: null, team_b_score: 1,
    status: "completed",
    scheduled_at: "2026-04-06T17:00:00Z",
    winner_id: 4,
    games: [],
  },

  // ── Upper Bracket Round 2 ─────────────────────────────────
  {
    id: 5,
    championship_id: 1,
    bracket_side: "upper",
    round: "UB R2",
    round_order: 2,
    match_number: 1,
    team_a_id: 1, team_a_name: "Wolves BR",       team_a_logo: null, team_a_score: 2,
    team_b_id: 2, team_b_name: "Dark Knights",    team_b_logo: null, team_b_score: 0,
    status: "completed",
    scheduled_at: "2026-04-08T15:00:00Z",
    winner_id: 1,
    games: [],
  },
  {
    id: 6,
    championship_id: 1,
    bracket_side: "upper",
    round: "UB R2",
    round_order: 2,
    match_number: 2,
    team_a_id: 3, team_a_name: "Phantom Esports", team_a_logo: null, team_a_score: 1,
    team_b_id: 4, team_b_name: "Red Storm",       team_b_logo: null, team_b_score: 2,
    status: "completed",
    scheduled_at: "2026-04-08T17:00:00Z",
    winner_id: 4,
    games: [],
  },

  // ── Upper Bracket Final ───────────────────────────────────
  {
    id: 7,
    championship_id: 1,
    bracket_side: "upper",
    round: "UB Final",
    round_order: 3,
    match_number: 1,
    team_a_id: 1, team_a_name: "Wolves BR",       team_a_logo: null, team_a_score: 0,
    team_b_id: 4, team_b_name: "Red Storm",       team_b_logo: null, team_b_score: 0,
    status: "scheduled",
    scheduled_at: "2026-04-13T15:00:00Z",
    winner_id: null,
    games: [],
  },

  // ── Lower Bracket Round 1 ─────────────────────────────────
  {
    id: 8,
    championship_id: 1,
    bracket_side: "lower",
    round: "LB R1",
    round_order: 4,
    match_number: 1,
    team_a_id: 8, team_a_name: "Iron Wolves",     team_a_logo: null, team_a_score: 0,
    team_b_id: 7, team_b_name: "Eclipse Gaming",  team_b_logo: null, team_b_score: 2,
    status: "completed",
    scheduled_at: "2026-04-07T15:00:00Z",
    winner_id: 7,
    games: [],
  },
  {
    id: 9,
    championship_id: 1,
    bracket_side: "lower",
    round: "LB R1",
    round_order: 4,
    match_number: 2,
    team_a_id: 6, team_a_name: "Neon Renegades",  team_a_logo: null, team_a_score: 1,
    team_b_id: 5, team_b_name: "Zero Hour",       team_b_logo: null, team_b_score: 2,
    status: "completed",
    scheduled_at: "2026-04-07T17:00:00Z",
    winner_id: 5,
    games: [],
  },

  // ── Lower Bracket Round 2 ─────────────────────────────────
  {
    id: 10,
    championship_id: 1,
    bracket_side: "lower",
    round: "LB R2",
    round_order: 5,
    match_number: 1,
    team_a_id: 2, team_a_name: "Dark Knights",    team_a_logo: null, team_a_score: 0,
    team_b_id: 7, team_b_name: "Eclipse Gaming",  team_b_logo: null, team_b_score: 0,
    status: "scheduled",
    scheduled_at: "2026-04-12T15:00:00Z",
    winner_id: null,
    games: [],
  },
  {
    id: 11,
    championship_id: 1,
    bracket_side: "lower",
    round: "LB R2",
    round_order: 5,
    match_number: 2,
    team_a_id: 3, team_a_name: "Phantom Esports", team_a_logo: null, team_a_score: 0,
    team_b_id: 5, team_b_name: "Zero Hour",       team_b_logo: null, team_b_score: 0,
    status: "scheduled",
    scheduled_at: "2026-04-12T17:00:00Z",
    winner_id: null,
    games: [],
  },

  // ── Lower Bracket Semi ────────────────────────────────────
  {
    id: 12,
    championship_id: 1,
    bracket_side: "lower",
    round: "LB Semi",
    round_order: 6,
    match_number: 1,
    team_a_id: null, team_a_name: "TBD",          team_a_logo: null, team_a_score: 0,
    team_b_id: null, team_b_name: "TBD",          team_b_logo: null, team_b_score: 0,
    status: "scheduled",
    scheduled_at: "2026-04-19T15:00:00Z",
    winner_id: null,
    games: [],
  },

  // ── Lower Bracket Final ───────────────────────────────────
  {
    id: 13,
    championship_id: 1,
    bracket_side: "lower",
    round: "LB Final",
    round_order: 7,
    match_number: 1,
    team_a_id: null, team_a_name: "TBD",          team_a_logo: null, team_a_score: 0,
    team_b_id: null, team_b_name: "TBD",          team_b_logo: null, team_b_score: 0,
    status: "scheduled",
    scheduled_at: "2026-04-20T15:00:00Z",
    winner_id: null,
    games: [],
  },

  // ── Grand Final ───────────────────────────────────────────
  {
    id: 14,
    championship_id: 1,
    bracket_side: "grand_final",
    round: "Grand Final",
    round_order: 8,
    match_number: 1,
    team_a_id: null, team_a_name: "TBD",          team_a_logo: null, team_a_score: 0,
    team_b_id: null, team_b_name: "TBD",          team_b_logo: null, team_b_score: 0,
    status: "scheduled",
    scheduled_at: "2026-04-26T15:00:00Z",
    winner_id: null,
    games: [],
  },
]

// ─── Champion Stats (agregado Season 1) ───────────────────────
export const mockChampionStats: ChampionStat[] = [
  { champion_name: "Thresh",    picks: 3, bans: 5, wins: 3, losses: 0, win_rate: 100 },
  { champion_name: "Jinx",      picks: 2, bans: 3, wins: 2, losses: 0, win_rate: 100 },
  { champion_name: "Lee Sin",   picks: 1, bans: 6, wins: 1, losses: 0, win_rate: 100 },
  { champion_name: "Hecarim",   picks: 1, bans: 2, wins: 1, losses: 0, win_rate: 100 },
  { champion_name: "Kalista",   picks: 1, bans: 4, wins: 1, losses: 0, win_rate: 100 },
  { champion_name: "Orianna",   picks: 2, bans: 2, wins: 1, losses: 1, win_rate: 50  },
  { champion_name: "Jhin",      picks: 1, bans: 3, wins: 1, losses: 0, win_rate: 100 },
  { champion_name: "Syndra",    picks: 1, bans: 4, wins: 1, losses: 0, win_rate: 100 },
  { champion_name: "LeBlanc",   picks: 1, bans: 3, wins: 0, losses: 1, win_rate: 0   },
  { champion_name: "Darius",    picks: 3, bans: 2, wins: 0, losses: 3, win_rate: 0   },
  { champion_name: "Garen",     picks: 1, bans: 0, wins: 1, losses: 0, win_rate: 100 },
  { champion_name: "Aphelios",  picks: 1, bans: 5, wins: 1, losses: 0, win_rate: 100 },
  { champion_name: "Xayah",     picks: 1, bans: 2, wins: 1, losses: 0, win_rate: 100 },
  { champion_name: "Rakan",     picks: 1, bans: 2, wins: 1, losses: 0, win_rate: 100 },
  { champion_name: "Zed",       picks: 1, bans: 4, wins: 0, losses: 1, win_rate: 0   },
  { champion_name: "Tristana",  picks: 1, bans: 1, wins: 1, losses: 0, win_rate: 100 },
  { champion_name: "Azir",      picks: 1, bans: 3, wins: 1, losses: 0, win_rate: 100 },
  { champion_name: "Katarina",  picks: 1, bans: 1, wins: 0, losses: 1, win_rate: 0   },
]

// ─── Pix ──────────────────────────────────────────────────────
export const mockPixPayment = {
  qr_code: "00020126580014BR.GOV.BCB.PIX0136example-pix-key-arenabr5204000053039865802BR5913ArenaBR LTDA6009SAO PAULO62070503***6304ABCD",
  qr_code_url: "https://placehold.co/200x200/0F1823/C89B3C?text=PIX+QR",
  amount: 100.0,
  expires_at: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
}
